Field alias support
timkendall/tql pull request #110
Opened 2022-04-18 17:30 UTC by lorefnon

This extends the API to support field aliasing, which is quite necessary when same field has to be fetched multiple times with different args/selections. 

Usage:

```ts
const selection = query(t => [
    t.images({}, t => [
        t.name()
    ]).as("photos")
]).toQuery({ queryName: "fetchPhotos" })
```

2022-04-29 02:16 UTC, timkendall requested changes
This is awesome, been meaning to get around to this! Please add new [type-level test suite](https://github.com/timkendall/tql/tree/master/test-d) for this functionality in `field-alias.test-d.ts` (or similar) and we can get this merged. Appreciate the work.

2022-04-29 06:01 UTC, lorefnon commented
@timkendall Thanks. I have added the type test.

2022-04-30 06:18 UTC, timkendall approved these changes

2022-04-30 06:19 UTC, merged

2022-04-30 06:24 UTC, timkendall commented
Published as @timkendall/tql@1.0.0-rc.8, @timkendall/tql@beta, @timkendall/tql-gen@1.0.0-rc.8, @timkendall/tql-gen@latest